spring:
  profiles:
    active: dev
  config:
    import: "classpath:config.properties"
token:
  ByteLength: 128
  validity:
    Mvola: ${MVOLA_VALIDITY_TOKEN}
    AirtelMoney: ${AIRTELMONEY_VALIDITY_TOKEN}
    OrangeMoney: ${ORANGEMONEY_VALIDITY_TOKEN}
  authorization:
    Mvola: ${MVOLA_AUTHORIZATION}
    AirtelMoney: ${AIRTELMONEY_AUTHORIZATION}
    OrangeMoney: ${ORANGEMONEY_AUTHORIZATION}
  identity:
    AirtelMoney: ${AIRTELMONEY_ID}
    GrantType: "client_credentials"
server:
  servlet:
    context-path: "/api/mock"
