spring:
  profiles:
    active: dev
  config:
    import: "classpath:config.properties"
token:
  ByteLength: ${BYTE_LENGTH}
  validity:
    Mvola: ${MVOLA_VALIDITY_TOKEN}
    AirtelMoney: ${AIRTELMONEY_VALIDITY_TOKEN}
    OrangeMoney: ${ORANGEMONEY_VALIDITY_TOKEN}
  authorization:
    Mvola: ${MVOLA_AUTHORIZATION}
    AirtelMoney: ${AIRTELMONEY_AUTHORIZATION}
    OrangeMoney: ${ORANGEMONEY_AUTHORIZATION}
  identity:
    AirtelMoney: ${AIRTELMONEY_ID}
    GrantType: ${IDENTITY_GRANT_TYPE}
currency:
  Mvola: ${MVOLA_CURRENCY}
  OrangeMoney: ${ORANGEMONEY_CURRENCY}
amount:
  Mvola: ${MVOLA_MINIMAL_AMOUNT}
  AirtelMoney: ${AIRTELMONEY_MINIMAL_AMOUNT}
  OrangeMoney: ${ORANGEMONEY_MINIMAL_AMOUNT}
server:
  servlet:
    context-path: "/api/mock"
