spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATABASE_URL_PROD}
    username: ${DATABASE_USERNAME_PROD}
    password: ${DATABASE_PASSWORD_PROD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  port: 3000