DATABASE_URL_DEV=jdbc:mysql://localhost:3306/mockserver25
DATABASE_USERNAME_DEV=root
DATABASE_PASSWORD_DEV=root

DATABASE_URL_PROD=jdbc:mysql://localhost:3306/mockserver25
DATABASE_USERNAME_PROD=root
DATABASE_PASSWORD_PROD=root

DATABASE_URL_TEST=jdbc:h2:mem:mockserver25
DATABASE_USERNAME_TEST=sa
DATABASE_PASSWORD_TEST=1234

AIRTELMONEY_ID=ed52af02-596c-42dc-bb12-0c90fcafb717

MVOLA_AUTHORIZATION=emZpWGowakdiVzFNQTJucEVfR1EyaG9sdTBrYTpobnVYQXlvT3RwcnpXNXZtZG5wTndiQVV4Vm9h
AIRTELMONEY_AUTHORIZATION=31179cd6-21f8-4636-8868-21133f6f06f5
ORANGEMONEY_AUTHORIZATION=M2MxV204NEF0NmFqbVU1Y0FxRENBdDBlUDZVcUllTEs6QklSNW14ZDgwYTlyTGRrTQ==

MVOLA_VALIDITY_TOKEN=3600
AIRTELMONEY_VALIDITY_TOKEN=180
ORANGEMONEY_VALIDITY_TOKEN=3600